# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsclean < Formula
  desc "Clean unused AMIs, unattached EBS volumes, and other stale AWS resources"
  homepage "https://github.com/steffakasid/trivy-project-scanner"
  version "1.14.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/awsclean/releases/download/v1.14.1/awsclean_1.14.1_darwin_amd64.tar.gz"
      sha256 "6a8b104f71d702f61408d39917fc3d9589bb6988710a679a30203186d0a08291"

      def install
        bin.install "awsclean"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/awsclean/releases/download/v1.14.1/awsclean_1.14.1_darwin_arm64.tar.gz"
      sha256 "976629daf30439730613800fec176a30b000da7d4350b04def88fd7ec9c86962"

      def install
        bin.install "awsclean"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/awsclean/releases/download/v1.14.1/awsclean_1.14.1_linux_amd64.tar.gz"
        sha256 "e2b7caf6b3fed29863d2548c562d4f0fe0e9d67febd01cd8079d330ce66220de"

        def install
          bin.install "awsclean"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/awsclean/releases/download/v1.14.1/awsclean_1.14.1_linux_arm64.tar.gz"
        sha256 "209b9b8c742050abab720ff5c82b2f1502de680c78b4152ffdd6d4d4336cb0ff"

        def install
          bin.install "awsclean"
        end
      end
    end
  end
end
