# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dof < Formula
  desc "Manage dotfiles in a bare Git repository"
  homepage "https://github.com/steffakasid/trivy-project-scanner"
  version "1.5.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/dof/releases/download/v1.5.0/dof_1.5.0_darwin_amd64.tar.gz"
      sha256 "257b05d9fa5504d281cc9663d46da9f65bc8242357cf05dc7deea34612f6aec6"

      def install
        bin.install "dof"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/dof/releases/download/v1.5.0/dof_1.5.0_darwin_arm64.tar.gz"
      sha256 "c22783f7f99b6652ac850af9115e87fb788fd53ac6ccf48c989c7b201315601a"

      def install
        bin.install "dof"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/dof/releases/download/v1.5.0/dof_1.5.0_linux_amd64.tar.gz"
        sha256 "200eb11b8ab84185bac1137ce14b5c22f0fddba260e2074109627dfb429c9d4a"

        def install
          bin.install "dof"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/dof/releases/download/v1.5.0/dof_1.5.0_linux_arm64.tar.gz"
        sha256 "805972a54cf253bc9ac218b8fa1cce844a795f0891fe071951f742aa662a4372"

        def install
          bin.install "dof"
        end
      end
    end
  end
end
