# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dof < Formula
  desc "Manage dotfiles in a bare Git repository"
  homepage "https://github.com/steffakasid/trivy-project-scanner"
  version "1.5.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/dof/releases/download/v1.5.1/dof_1.5.1_darwin_amd64.tar.gz"
      sha256 "5d40f3f596f663dc2d95015de28336e2d0accd328f29e71200b333df1eb4b317"

      def install
        bin.install "dof"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/dof/releases/download/v1.5.1/dof_1.5.1_darwin_arm64.tar.gz"
      sha256 "966f1513c6d25ce2179d1626ebe05b434955136e17243f09c158870631d6ad2d"

      def install
        bin.install "dof"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/dof/releases/download/v1.5.1/dof_1.5.1_linux_amd64.tar.gz"
        sha256 "7e8d1f8889c526ffa18b81469a72ed5a2d60cad08748df8c9439329987643bc6"

        def install
          bin.install "dof"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/dof/releases/download/v1.5.1/dof_1.5.1_linux_arm64.tar.gz"
        sha256 "eda342175d0d9a48440ccebde6b11c8da6acb184b89275ffbd7cff1b028c147f"

        def install
          bin.install "dof"
        end
      end
    end
  end
end
