# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dof < Formula
  desc "Manage dotfiles in a bare Git repository"
  homepage "https://github.com/steffakasid/trivy-project-scanner"
  version "1.3.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/dof/releases/download/v1.3.0/dof_1.3.0_darwin_amd64.tar.gz"
      sha256 "3cfbcd594d42a9ba5834573f0d99780a1d8cca07102c6a9eb201164202cbdf04"

      def install
        bin.install "dof"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/dof/releases/download/v1.3.0/dof_1.3.0_darwin_arm64.tar.gz"
      sha256 "dc7219adfc0e04667c6968aa0f4d70d5f66dc17d0f36bccf73ec567d9b5e7248"

      def install
        bin.install "dof"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/dof/releases/download/v1.3.0/dof_1.3.0_linux_amd64.tar.gz"
        sha256 "757ad2a3fcf3890b1c8a5f9e7bb9f9a3800ca28fb31cc655401df4c2f9975cbb"

        def install
          bin.install "dof"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/dof/releases/download/v1.3.0/dof_1.3.0_linux_arm64.tar.gz"
        sha256 "fe263713ecbe6ef7eb8435e9c5cbfb141884b76c2727b5d13d893ee44b2e1f67"

        def install
          bin.install "dof"
        end
      end
    end
  end
end
