# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Govital < Formula
  desc "Check Go dependencies for updates and maintenance activity"
  homepage "https://github.com/steffakasid/govital"
  version "1.0.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/govital/releases/download/v1.0.1/govital_1.0.1_darwin_amd64.tar.gz"
      sha256 "db7843df4e7442c29b4f8d1396d051c5569fd8a35da2bbe9b6ac0cf28c7bbf3c"

      def install
        bin.install "govital"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/govital/releases/download/v1.0.1/govital_1.0.1_darwin_arm64.tar.gz"
      sha256 "71252911f051845c40c94ec94fd24955f2ec8f34b756b4c5838bd0a431de01aa"

      def install
        bin.install "govital"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/govital/releases/download/v1.0.1/govital_1.0.1_linux_amd64.tar.gz"
        sha256 "146f162c3af0c1f78eb5c4226a946809075b97f9e8efbe1b77cbcaa43f2f3d30"

        def install
          bin.install "govital"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/govital/releases/download/v1.0.1/govital_1.0.1_linux_arm64.tar.gz"
        sha256 "5f149a74fd0f7df80558107e1b0ea5ec4eda00a9e8e95d852fa2e83ff3e25573"

        def install
          bin.install "govital"
        end
      end
    end
  end
end
