# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Govital < Formula
  desc "Check Go dependencies for updates and maintenance activity"
  homepage "https://github.com/steffakasid/govital"
  version "1.2.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/govital/releases/download/v1.2.1/govital_1.2.1_darwin_amd64.tar.gz"
      sha256 "c2e6f782fd85a98609a5caef3ea89def40483effb8c95b34e69334c1a9bbcdf8"

      def install
        bin.install "govital"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/govital/releases/download/v1.2.1/govital_1.2.1_darwin_arm64.tar.gz"
      sha256 "5093acaed1efb8386aecda3ebd4f6b0b5f9ef8df6cc33cb52b1911c5ff210b53"

      def install
        bin.install "govital"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/govital/releases/download/v1.2.1/govital_1.2.1_linux_amd64.tar.gz"
        sha256 "82378480be0ec56a849fba0139dbe0ff02c57c98aae442e65e3d8a625c2a54d7"

        def install
          bin.install "govital"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/govital/releases/download/v1.2.1/govital_1.2.1_linux_arm64.tar.gz"
        sha256 "83c9bb2be7b13f2a243f8dfc390c89e5ced700a606715def77cdba37faef0d3c"

        def install
          bin.install "govital"
        end
      end
    end
  end
end
