# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hdc < Formula
  desc "Helmfile Dependency Checker - Verify Helm chart dependencies are up-to-date and actively maintained"
  homepage "https://github.com/steffakasid/helmfile-dependency-checker"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/helmfile-dependency-checker/releases/download/v1.1.0/hdc_1.1.0_darwin_amd64.tar.gz"
      sha256 "9c6220acb8d87274fa7cae9454e7b0e79a410c2d673cc05c459467b44a69b74d"

      def install
        bin.install "hdc"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/helmfile-dependency-checker/releases/download/v1.1.0/hdc_1.1.0_darwin_arm64.tar.gz"
      sha256 "318723233b1f0745f0b4153b2920f8cce0456a4b4097e632165ba6e745612966"

      def install
        bin.install "hdc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/helmfile-dependency-checker/releases/download/v1.1.0/hdc_1.1.0_linux_amd64.tar.gz"
        sha256 "8f36a8a5eee5d11682b9c11acfb0ebeb829f38c20c739fa775b7fd85e43a4e11"

        def install
          bin.install "hdc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/helmfile-dependency-checker/releases/download/v1.1.0/hdc_1.1.0_linux_arm64.tar.gz"
        sha256 "e2af5a15e1d3bf07d6c75f16e7579142ed5779269ec8b99f702bdeaf6c0f102e"

        def install
          bin.install "hdc"
        end
      end
    end
  end

  def caveats
    <<~EOS
      HDC is a standalone CLI tool for checking Helm chart dependencies.

      Quick start:
        hdc check helmfile.yaml

      For more information:
        https://github.com/steffakasid/helmfile-dependency-checker
    EOS
  end

  test do
    system "#{bin}/hdc", "version"
  end
end
