# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hdc < Formula
  desc "Check Helmfile chart dependencies for updates and maintenance status"
  homepage "https://github.com/steffakasid/helmfile-dependency-checker"
  version "1.1.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/helmfile-dependency-checker/releases/download/v1.1.1/hdc_1.1.1_darwin_amd64.tar.gz"
      sha256 "4777b6e02718697145c5d6c54e28e2880b91e782b183da688128081d7ce6f14b"

      def install
        bin.install "hdc"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/helmfile-dependency-checker/releases/download/v1.1.1/hdc_1.1.1_darwin_arm64.tar.gz"
      sha256 "b67db3745ac229ccc232c6b3c096334affe09dca7a90555269b1035e8518eb45"

      def install
        bin.install "hdc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/helmfile-dependency-checker/releases/download/v1.1.1/hdc_1.1.1_linux_amd64.tar.gz"
        sha256 "1ed164c14cec3e2be2c9f5c7c164d58f4a0517db15dba353c04a78fc8cf617cc"

        def install
          bin.install "hdc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/helmfile-dependency-checker/releases/download/v1.1.1/hdc_1.1.1_linux_arm64.tar.gz"
        sha256 "5a125a09542471ab6ed1269fc6116db2f8df03056c19a07571e6bc0ce248dee5"

        def install
          bin.install "hdc"
        end
      end
    end
  end

  def caveats
    <<~EOS
      HDC is a standalone CLI tool for checking Helm chart dependencies.

      Quick start:
        hdc check helmfile.yaml

      For more information:
        https://github.com/steffakasid/helmfile-dependency-checker
    EOS
  end

  test do
    system "#{bin}/hdc", "version"
  end
end
