# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hdc < Formula
  desc "Check Helmfile chart dependencies for updates and maintenance status"
  homepage "https://github.com/steffakasid/helmfile-dependency-checker"
  version "1.1.3"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/helmfile-dependency-checker/releases/download/v1.1.3/hdc_1.1.3_darwin_amd64.tar.gz"
      sha256 "89b5823fd586469cc5f8aee5d94150e21bb8e9ff539fd909c98b443a5b613bb4"

      def install
        bin.install "hdc"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/helmfile-dependency-checker/releases/download/v1.1.3/hdc_1.1.3_darwin_arm64.tar.gz"
      sha256 "983a6929e45b657f2a63438b821be30bf525bc3828241da84ce0a751471ee791"

      def install
        bin.install "hdc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/helmfile-dependency-checker/releases/download/v1.1.3/hdc_1.1.3_linux_amd64.tar.gz"
        sha256 "e36319ea946c5acb525f7cae33b4b7820336f63d1728cd5d30e548381924bc0a"

        def install
          bin.install "hdc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/helmfile-dependency-checker/releases/download/v1.1.3/hdc_1.1.3_linux_arm64.tar.gz"
        sha256 "b6926c032a80d8817dc6f076140e196af712ce4e9a52042438a306ab0345db88"

        def install
          bin.install "hdc"
        end
      end
    end
  end

  def caveats
    <<~EOS
      HDC is a standalone CLI tool for checking Helm chart dependencies.

      Quick start:
        hdc check helmfile.yaml

      For more information:
        https://github.com/steffakasid/helmfile-dependency-checker
    EOS
  end

  test do
    system "#{bin}/hdc", "version"
  end
end
