# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCo < Formula
  desc "Switch between separate kubeconfig files from kubectl"
  homepage "https://github.com/steffakasid/kubectl-go"
  version "1.1.2"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/kubectl-co/releases/download/v1.1.2/kubectl-co_1.1.2_darwin_amd64.tar.gz"
      sha256 "b8c96b67e4ef0a382b14304f86c5a688d1a2b7fa12fba7fdc7c22ee80b4172e1"

      def install
        bin.install "kubectl-co"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/kubectl-co/releases/download/v1.1.2/kubectl-co_1.1.2_darwin_arm64.tar.gz"
      sha256 "febc07e132b725e13fadfad7d176f9963c2540d7fd157122d3a9d1cafb41dd79"

      def install
        bin.install "kubectl-co"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/kubectl-co/releases/download/v1.1.2/kubectl-co_1.1.2_linux_amd64.tar.gz"
        sha256 "dd894fd1ae863499493128468d96ed673057a5e430f17d7a62966a43f68d081f"

        def install
          bin.install "kubectl-co"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/kubectl-co/releases/download/v1.1.2/kubectl-co_1.1.2_linux_arm64.tar.gz"
        sha256 "058059ab1e9dfed5d4084eb538ddb139d71006f59e60c294c9d90cb67457a2a8"

        def install
          bin.install "kubectl-co"
        end
      end
    end
  end
end
