# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCo < Formula
  desc "Switch between separate kubeconfig files from kubectl"
  homepage "https://github.com/steffakasid/kubectl-go"
  version "1.0.2"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/kubectl-co/releases/download/v1.0.2/kubectl-co_1.0.2_darwin_amd64.tar.gz"
      sha256 "13a20c72d467adbf7c5c44a32348c41ae2badbe44ffa9702d5fd435871da917d"

      def install
        bin.install "kubectl-co"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/kubectl-co/releases/download/v1.0.2/kubectl-co_1.0.2_darwin_arm64.tar.gz"
      sha256 "a1f263d4c7916e015801b738de9fd1d1ab76bbf0979e66204ae43bcfe8696d1e"

      def install
        bin.install "kubectl-co"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/kubectl-co/releases/download/v1.0.2/kubectl-co_1.0.2_linux_amd64.tar.gz"
        sha256 "e0d8d83addf2771d07c2ecd26f5d4d3711579ad5613f9099899c78d452b5e3de"

        def install
          bin.install "kubectl-co"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/kubectl-co/releases/download/v1.0.2/kubectl-co_1.0.2_linux_arm64.tar.gz"
        sha256 "da52f950117e3637937c37d89f83829522c7ae4d48c3cb774498ce163ae132bf"

        def install
          bin.install "kubectl-co"
        end
      end
    end
  end
end
