# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCo < Formula
  desc "Switch between separate kubeconfig files from kubectl"
  homepage "https://github.com/steffakasid/kubectl-go"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/kubectl-co/releases/download/v1.1.0/kubectl-co_1.1.0_darwin_amd64.tar.gz"
      sha256 "595c8bbd5a9527349b76b00e7d45c05df3e020ae46a9d09c92d144ea548b9a08"

      def install
        bin.install "kubectl-co"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/kubectl-co/releases/download/v1.1.0/kubectl-co_1.1.0_darwin_arm64.tar.gz"
      sha256 "c6d534a6bfe2e171a1af815eee160789cc3aa6c418fac0ebe51c0e456f9a18bb"

      def install
        bin.install "kubectl-co"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/kubectl-co/releases/download/v1.1.0/kubectl-co_1.1.0_linux_amd64.tar.gz"
        sha256 "9f0f8c5de36aaaffdad761ef0b9ce1a3030547b6d17d5bb2cf517ddf8ecbacfe"

        def install
          bin.install "kubectl-co"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/kubectl-co/releases/download/v1.1.0/kubectl-co_1.1.0_linux_arm64.tar.gz"
        sha256 "a2d24647c6614b7d46c3d012836f4034282aa6cca3af020c2205586e8ebb5428"

        def install
          bin.install "kubectl-co"
        end
      end
    end
  end
end
