# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wiper < Formula
  desc "Delete configured files and folders by name or pattern"
  homepage "https://github.com/steffakasid/wiper"
  version "1.1.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/wiper/releases/download/v1.1.1/wiper_1.1.1_darwin_amd64.tar.gz"
      sha256 "7be8e9bd427a4544a6f9fc2aaa645feda2b8429867c7ce841a2878b2d25c8b90"

      def install
        bin.install "wiper"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/wiper/releases/download/v1.1.1/wiper_1.1.1_darwin_arm64.tar.gz"
      sha256 "403fe1ccc95001c96d42922f16824ca4f68415cc19a30f0c6b53edf3c3694467"

      def install
        bin.install "wiper"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/wiper/releases/download/v1.1.1/wiper_1.1.1_linux_amd64.tar.gz"
        sha256 "c9b1aee86a4a4e1890fa58439ba4e72e03e63b46795d19f11df635759bae37bb"

        def install
          bin.install "wiper"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/wiper/releases/download/v1.1.1/wiper_1.1.1_linux_arm64.tar.gz"
        sha256 "2c87d9a1ce27149622a73739a43040abbb7ece91d92c3de8f3ab5422726f2d88"

        def install
          bin.install "wiper"
        end
      end
    end
  end
end
